In [56]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('framingham.csv')
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [49]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [50]:
df = df.dropna()
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [51]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [67]:
train_data = df.values
y = df.iloc[:,[-1]]
x=train_data[:,:-1]
x

array([[  1.  ,  39.  ,   4.  , ...,  26.97,  80.  ,  77.  ],
       [  0.  ,  46.  ,   2.  , ...,  28.73,  95.  ,  76.  ],
       [  1.  ,  48.  ,   1.  , ...,  25.34,  75.  ,  70.  ],
       ...,
       [  1.  ,  50.  ,   1.  , ...,  25.97,  66.  ,  86.  ],
       [  1.  ,  51.  ,   3.  , ...,  19.71,  65.  ,  68.  ],
       [  0.  ,  52.  ,   2.  , ...,  21.47,  80.  , 107.  ]])

In [68]:
y

TenYearCHD
0              0
1              0
2              0
3              1
4              0
...          ...
4231           0
4232           1
4233           1
4234           0
4237           0

[3656 rows x 1 columns]

In [69]:
x = np.vstack((np.ones((x.shape[0],)),x.T)).T
x

array([[  1.  ,   1.  ,  39.  , ...,  26.97,  80.  ,  77.  ],
       [  1.  ,   0.  ,  46.  , ...,  28.73,  95.  ,  76.  ],
       [  1.  ,   1.  ,  48.  , ...,  25.34,  75.  ,  70.  ],
       ...,
       [  1.  ,   1.  ,  50.  , ...,  25.97,  66.  ,  86.  ],
       [  1.  ,   1.  ,  51.  , ...,  19.71,  65.  ,  68.  ],
       [  1.  ,   0.  ,  52.  , ...,  21.47,  80.  , 107.  ]])

In [78]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [88]:
def model(x,y,learning_rate,iteration):
    m=y.size
    theta = np.zeros((x.shape[1],1))
    cost_list=[]
    for i in range(iteration):
        y_pred=sigmoid(np.dot(x,theta))
        cost=(-1/m)*(np.dot((np.log(y_pred)).T,y)+np.dot((np.log(1-y_pred)).T,(1-y)))
        dtheta=(1/m)*np.dot(x.T,y_pred-y)
        theta = theta-learning_rate*dtheta
        cost_list.append(cost)
        if(i%(iteration/10)==0):
            print ("cost is: ",cost)
    return theta,cost_list 

In [100]:
iteration = 100000
learning_rate=0.0001
theta, cost_list = model(x,y,learning_rate,iteration)

cost is:  [[0.69314718]]
cost is:  [[0.41192374]]
cost is:  [[0.41064184]]
cost is:  [[0.40960521]]
cost is:  [[0.40872438]]
cost is:  [[0.40796388]]
cost is:  [[0.40729795]]
cost is:  [[0.4067071]]
cost is:  [[0.40617652]]
cost is:  [[0.40569485]]


In [92]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x, y)
coefficients = model1.coef_
intercept = model1.intercept_

# Display results
print("Coefficients:", coefficients)
print("Intercept:", intercept)

C:\Users\vinay\.anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Coefficients: [[-0.09414357  0.11536015  0.02977943 -0.34738758 -0.05500476  0.01918882
   0.03850227  0.01314336  0.23317563  0.04070235 -0.00058903  0.0142944
  -0.00871169 -0.06748032 -0.0315017   0.00490791]]
Intercept: [-0.09417242]


C:\Users\vinay\.anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [93]:
theta

array([[-0.07241239],
       [ 0.08540266],
       [ 0.02610667],
       [-0.17657874],
       [-0.03952584],
       [ 0.01698774],
       [ 0.02959378],
       [ 0.0102595 ],
       [ 0.17189028],
       [ 0.03085955],
       [-0.00233359],
       [ 0.02234556],
       [-0.02526327],
       [-0.05062101],
       [-0.02991628],
       [ 0.00439175]])

In [144]:
b = np.full((x.shape[0],1),model1.intercept_)
y_pred=sigmoid(np.dot(x,model1.coef_.T)+b)
print((-1/m)*(np.dot((np.log(y_pred)).T,y)+np.dot((np.log(1-y_pred)).T,(1-y))))

[[0.1480094]]


In [98]:
count_ones = df['TenYearCHD'].value_counts()[1]
count_zeros = df['TenYearCHD'].value_counts()[0]
print(count_ones , count_zeros)

557 3099


In [106]:
Y=sigmoid(np.dot(x,theta))
Y

array([[0.04971765],
       [0.0425666 ],
       [0.17178842],
       ...,
       [0.33735761],
       [0.30673711],
       [0.13947053]])

In [162]:
threshold = 0.4

In [163]:
Y_pred=(Y>threshold).astype(int)
Y_actual=y.values
Y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [164]:
import numpy as np

TP = 0  # True Positives
FP = 0  # False Positives
TN = 0  # True Negatives
FN = 0  # False Negatives

for actual, pred in zip(Y_actual, Y_pred):
    if actual == 1 and pred == 1:
        TP += 1
    elif actual == 0 and pred == 1:
        FP += 1
    elif actual == 0 and pred == 0:
        TN += 1
    elif actual == 1 and pred == 0:
        FN += 1

conf_matrix = np.array([[TN, FP], [FN, TP]])

print("Confusion Matrix:")
print(conf_matrix)

accuracy = (TP + TN) / len(Y_actual)
print("\nAccuracy:", accuracy)

precision = TP / (TP + FP) if (TP + FP) > 0 else 0
print("Precision:", precision)

recall = TP / (TP + FN) if (TP + FN) > 0 else 0
print("Recall:", recall)

f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
print("F1 Score:", f1)


Confusion Matrix:
[[3054   45]
 [ 510   47]]

Accuracy: 0.8481947483588621
Precision: 0.5108695652173914
Recall: 0.0843806104129264
F1 Score: 0.1448382126348228


In [165]:
y_ = (y_pred>threshold).astype(int)
y_

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [166]:
import numpy as np

TP = 0  # True Positives
FP = 0  # False Positives
TN = 0  # True Negatives
FN = 0  # False Negatives

for actual, pred in zip(Y_actual, y_):
    if actual == 1 and pred == 1:
        TP += 1
    elif actual == 0 and pred == 1:
        FP += 1
    elif actual == 0 and pred == 0:
        TN += 1
    elif actual == 1 and pred == 0:
        FN += 1

conf_matrix = np.array([[TN, FP], [FN, TP]])

print("Confusion Matrix:")
print(conf_matrix)

accuracy = (TP + TN) / len(Y_actual)
print("\nAccuracy:", accuracy)

precision = TP / (TP + FP) if (TP + FP) > 0 else 0
print("Precision:", precision)

recall = TP / (TP + FN) if (TP + FN) > 0 else 0
print("Recall:", recall)

f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
print("F1 Score:", f1)


Confusion Matrix:
[[3042   57]
 [ 508   49]]

Accuracy: 0.8454595185995624
Precision: 0.46226415094339623
Recall: 0.08797127468581688
F1 Score: 0.1478129713423831


In [167]:
y_lr = model1.predict(x)


In [168]:
import numpy as np

TP = 0  # True Positives
FP = 0  # False Positives
TN = 0  # True Negatives
FN = 0  # False Negatives

for actual, pred in zip(Y_actual, y_lr):
    if actual == 1 and pred == 1:
        TP += 1
    elif actual == 0 and pred == 1:
        FP += 1
    elif actual == 0 and pred == 0:
        TN += 1
    elif actual == 1 and pred == 0:
        FN += 1

conf_matrix = np.array([[TN, FP], [FN, TP]])

print("Confusion Matrix:")
print(conf_matrix)

accuracy = (TP + TN) / len(Y_actual)
print("\nAccuracy:", accuracy)

precision = TP / (TP + FP) if (TP + FP) > 0 else 0
print("Precision:", precision)

recall = TP / (TP + FN) if (TP + FN) > 0 else 0
print("Recall:", recall)

f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
print("F1 Score:", f1)

Confusion Matrix:
[[3088   11]
 [ 538   19]]

Accuracy: 0.8498358862144421
Precision: 0.6333333333333333
Recall: 0.03411131059245961
F1 Score: 0.0647359454855196
